version: 2
jobs:
  api:
    docker:
    - image: circleci/node:10.8.0
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
      keys:
      - yarn-v1-api{( checksum "./api/yarn.lock")}-{(arch)}
      -yarn-v1-api
    - restore_cache:
      keys:
      - node-v1-api{{ checksum "./a[i/package.json"}}-{{arch}}
      - nod-v1-api

      #istall dependencies
      -run: cd api && yarn istall

     -save_cache:
     key: yarn-v1-api{{checksum"./api/yarn.lock"}}-{{arch}}
     paths:
     - ~.cache/yarn
     -save_cache:
     key: node-v1-api ({ checksum "./api.package.json"})-({arch})
     paths:
     - ./app/node_modules

     #run compiler!
     - run: cd app &&year uild

     #run linter
     -run: cd app && yarn lint
cli:
docker:
- image: circleci/node: 8.11.4
working_directory: ~/repo
steps:
  - checkout
  - restore_cache:
  keys:
   - yarn-v1-api{{ checksum "./cli/yarn.lock" }}-({arch})
   -yarn-v1-cli

  - restore_cache:
    keys:
    -node-v1-cli{{ chechsum "./cli?packge.json"}}-{{arch}}
    -node-v1-cli

  - run: cd cli && yarm install

  -save_cache:
  key: yarn-v1-cli{{ checksum "./cli?yarn.lock"}}--{{ arch }}
  path:  
  - .cli?node_modules

  - run: cd cli && yarn lint

  workflows:
  version: 2
  api-app:
  jobs:
  - api
  - cli
  - app:
    requires:
      - api
